#!/bin/sh

password=$(cat /var/lib/boinc/gui_rpc_auth.cfg);

boinccmd --host localhost:31418 --passwd $password --set_run_mode always

password=$(cat /var/lib/boinc_2/gui_rpc_auth.cfg);

boinccmd --host localhost:31420 --passwd $password --set_run_mode always

password=$(cat /var/lib/boinc_3/gui_rpc_auth.cfg);

boinccmd --host localhost:31422 --passwd $password --set_run_mode always

#FAHClient --send-unpause
