.TH "EventDetectConfig" 3 "Tue Apr 15 2025" "Version 0.7.9.0" "idle_detect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventDetectConfig \- The \fBEventDetectConfig\fP class\&. This specializes the \fBConfig\fP class and implements the virtual method \fBProcessArgs()\fP for event_detect\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <event_detect\&.h>\fP
.PP
Inherits \fBConfig\fP\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBProcessArgs\fP () override"
.br
.RI "Private helper method used by ReadAndUpdateConfig\&. Note this is pure virtual\&. It must be implemented in a specialization of a derived class for use by a specific application\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBEventDetectConfig\fP class\&. This specializes the \fBConfig\fP class and implements the virtual method \fBProcessArgs()\fP for event_detect\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for idle_detect from the source code\&.
