.TH "IdleDetectConfig" 3 "Tue Apr 15 2025" "Version 0.7.9.0" "idle_detect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IdleDetectConfig \- The \fBIdleDetectConfig\fP class\&. This specializes the \fBConfig\fP class and implements the virtual method \fBProcessArgs()\fP for idle_detect\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <idle_detect\&.h>\fP
.PP
Inherits \fBConfig\fP\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBProcessArgs\fP () override"
.br
.RI "The is the \fBProcessArgs()\fP implementation for idle_detect\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBIdleDetectConfig\fP class\&. This specializes the \fBConfig\fP class and implements the virtual method \fBProcessArgs()\fP for idle_detect\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for idle_detect from the source code\&.
