.TH "ThreadException" 3 "Sun Apr 13 2025" "Version 0.7.7.0" "idle_detect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThreadException \- Threading Related Exceptions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <util\&.h>\fP
.PP
Inherits \fBEventIdleDetectException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadException\fP (const std::string &message)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Threading Related Exceptions\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for idle_detect from the source code\&.
