.TH "tinyformat::detail::convertToInt< T, convertible >" 3 "Sun Apr 27 2025" "Version 0.8.1.0" "idle_detect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::detail::convertToInt< T, convertible >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBinvoke\fP (const T &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for idle_detect from the source code\&.
