.TH "tinyformat::detail::FormatListN< 0 >" 3 "Sat Apr 12 2025" "Version 0.7" "idle_detect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::detail::FormatListN< 0 >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtinyformat::FormatList\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for idle_detect from the source code\&.
