.TH "tinyformat::detail::formatValueAsType< T, fmtT, true >" 3 "Sat Apr 12 2025" "Version 0.7" "idle_detect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::detail::formatValueAsType< T, fmtT, true >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinvoke\fP (std::ostream &out, const T &value)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for idle_detect from the source code\&.
