.TH "tinyformat::format_error" 3 "Sun Apr 20 2025" "Version 0.8.0.0" "idle_detect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::format_error
.SH SYNOPSIS
.br
.PP
.PP
Inherits runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformat_error\fP (const std::string &what)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for idle_detect from the source code\&.
