.TH "tinyformat::detail::is_wchar< const wchar_t * >" 3 "Sun Apr 27 2025" "Version 0.8.1.0" "idle_detect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::detail::is_wchar< const wchar_t * >
.SH SYNOPSIS
.br
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for idle_detect from the source code\&.
