.TH "tinyformat::detail::is_convertible< T1, T2 >::succeed" 3 "Tue Aug 19 2025" "Version 0.8.3.0" "idle_detect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::detail::is_convertible< T1, T2 >::succeed
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBdummy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for idle_detect from the source code\&.
