.TH "tinyformat::detail::formatValueAsType< T, fmtT, convertible >" 3 "Wed Apr 16 2025" "Version 0.7.11.0" "idle_detect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::detail::formatValueAsType< T, fmtT, convertible >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinvoke\fP (std::ostream &, const T &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for idle_detect from the source code\&.
