.TH "tinyformat::detail::FormatListN< N >" 3 "Sun Apr 13 2025" "Version 0.7.8.0" "idle_detect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::detail::FormatListN< N >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtinyformat::FormatList\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBFormatListN\fP (const Args &\&.\&.\&. args)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBFormatArg\fP \fBm_formatterStore\fP [N]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for idle_detect from the source code\&.
